[package]
name = "servicepoint-nexus"
version = "0.1.0"
edition = "2021"

[dependencies]
servicepoint = {git = "https://github.com/cccb/servicepoint", branch = "additional-grid-features"}
rand = "0.8.5"